#!/bin/sh

export GJS_PATH="/home/zeenix/jhbuild/share/gnome-maps/js${GJS_PATH:+:$GJS_PATH}"
export GI_TYPELIB_PATH="/home/zeenix/jhbuild/lib64/gnome-maps/girepository-1.0${GI_TYPELIB_PATH:+:$GI_TYPELIB_PATH}"
export LD_LIBRARY_PATH="/home/zeenix/jhbuild/lib64/gnome-maps${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

if test x"$GJS_DEBUG_OUTPUT" = x ; then
    export GJS_DEBUG_OUTPUT=stderr
fi

if test x"$GJS_DEBUG_TOPICS" = x ; then
    export GJS_DEBUG_TOPICS="JS ERROR;JS LOG"
fi

DEBUG_COMMAND=""
if test x"$MAPS_RUN_DEBUG" != x; then
    DEBUG_COMMAND="gdb --args"
fi

exec $DEBUG_COMMAND /home/zeenix/jhbuild/bin/gjs-console -I /home/zeenix/jhbuild/share/gnome-maps/js -c "const Main = imports.main; Main.start();" "$@"
